# Generated by Django 4.2.4 on 2023-09-02 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("Friend", "Friend"),
                            ("Family", "Family"),
                            ("Relative", "Relative"),
                            ("Colleague", "Colleague"),
                            ("Other", "Other"),
                        ],
                        default="Friend",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("photo", models.ImageField(blank=True, upload_to="photos/")),
                ("priority", models.IntegerField(default=1)),
                ("talked", models.BooleanField(default=False)),
                ("last_contact", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
